name: Backend Windows Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'src/backend/**'
      - 'src/gui/**'
      - 'src/setup/**'
      - 'CMakeLists.txt'
      - '.github/workflows/backend-build.yml'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure (CMake - fresh build dir)
        run: |
          if exist build rmdir /s /q build
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
        shell: cmd

      - name: Build (CMake/MSBuild)
        run: |
          cmake --build build --config Release -- /m
        shell: cmd

      # MSBuild step will fail the job automatically if errors occur

      - name: Archive build logs
        if: always()
        run: |
          echo Build completed with exit code %ERRORLEVEL% > build\\backend_build_summary.txt
          dir build /s > build\\tree.txt
        shell: cmd

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Aether-Backend-build-artifacts
          path: |
            build/**
